{
 "title": "Mini Observable K8s Platform",
 "tags": [
  "api",
  "platform"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "P95 Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx / total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "API Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"api\"}",
     "legendFormat": "up"
    }
   ]
  }
 ]
}